[package]
name = "serac"
version = "0.3.0"
edition = "2024"
description = "A static, modular, and light-weight serialization framework."
license = "CC-BY-NC-SA-4.0"
repository = "https://github.com/adinack/embedded-command"

[dependencies]
macros = { package = "embedded-command-macros", version = "0.3.0" }
fill-array = "0.2.1"

# for binary
panic-halt = { version = "1.0.0", optional = true }
cortex-m = { version = "0.7.7", optional = true }
cortex-m-rt = { version = "0.7.3", optional = true }
defmt = { version = "0.3.10", optional = true }

[features]
binary = ["dep:panic-halt", "dep:cortex-m", "dep:cortex-m-rt"]
defmt = ["dep:defmt"]

[[bin]]
name = "asm"
bench = false
test = false
required-features = ["binary"]
