[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
packit = []

[dependencies]
Inflector = "0.11.4"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.50", features = ["full"] }
