[package]
name = "embedded-command-macros"
version = "0.1.0"
edition = "2024"
description = "Macros for the embedded command crate family."
license = "CC-BY-NC-SA-4.0"
repository = "https://github.com/adinack/embedded-command"

[lib]
proc-macro = true

[features]
packit = []

[dependencies]
Inflector = "0.11.4"
proc-macro2 = "1.0.78"
quote = "1.0.35"
syn = { version = "2.0.50", features = ["full"] }
