[package]
name = "cookie-cutter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fill-array = "0.2.1"
macros = { path = "../macros" }
